# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [17]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Regression Model Evaluation

In [18]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [3]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [19]:
data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [20]:
# Your code here :
from sklearn.model_selection import train_test_split

X = data.drop('MEDV', axis=1)
y = data['MEDV']

X_train, X_test, y_train, y_test = train_test_split(
  X, y, 
  test_size=.2, 
  random_state=42)

print(X_train.shape, X_test.shape)

(404, 13) (102, 13)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [21]:
# Your code here :
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

LinearRegression()

## 3. Calculate and print R-squared for both the training and the testing set.

In [22]:
# Your code here :
from sklearn.metrics import r2_score

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

r2_train = r2_score(y_train, y_train_pred)
r2_test = r2_score(y_test, y_test_pred)

print(f"R2 Training: {r2_train}")
print(f"R2 Testing: {r2_test}")

R2 Training: 0.7508856358979673
R2 Testing: 0.6687594935356296

## 4. Calculate and print mean squared error for both the training and the testing set.

In [11]:
# Your code here :
from sklearn.metrics import mean_squared_error

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

mse_train = mean_squared_error(y_train, y_train_pred)
mse_test = mean_squared_error(y_test, y_test_pred)

print(f"Mean Squared Error Training: {mse_train}")
print(f"Mean Squared Error Testing: {mse_test}")

Mean Squared Error Training: 21.641412753226312
Mean Squared Error Testing: 24.29111947497369

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [13]:
# Your code here :
from sklearn.metrics import mean_absolute_error

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)

mae_train = mean_absolute_error(y_train, y_train_pred)
mae_test = mean_absolute_error(y_test, y_test_pred)

print(f"Mean Absolute Error Training: {mae_train}")
print(f"Mean Absolute Error Testing: {mae_test}")

Mean Absolute Error Training: 3.314771626783228
Mean Absolute Error Testing: 3.1890919658878603

## Classification Model Evaluation

In [24]:
from sklearn.datasets import load_iris
data = load_iris()

In [25]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [26]:
column_names = data.feature_names

In [33]:
df = pd.DataFrame(data['data'],columns=column_names)

In [34]:
df.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [35]:
target = pd.DataFrame(data.target)

In [36]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [37]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [ ]:
# Your code here 

X = df
y = target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [46]:
# Your code here :
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [67]:
# Your code here :
from sklearn.metrics import accuracy_score

y_pred_test = model.predict(X_test)
y_pred_train = model.predict(X_train)

accuracy_test = accuracy_score(y_test, y_pred_test)
accuracy_train = accuracy_score(y_train, y_pred_train)

print(f"The accuracy score for training: {accuracy_train}")
print(f"The accuracy score for testing: {accuracy_test}")

The accuracy score for training: 0.975
The accuracy score for testing: 1.0

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [68]:
# Your code here :
from sklearn.metrics import balanced_accuracy_score

bas_testing = balanced_accuracy_score(y_test, y_pred_test)
bas_training = balanced_accuracy_score(y_train, y_pred_train)

print(f"The balanced accuracy score for testing: {bas_testing}")
print(f"The balanced accuracy score for testing: {bas_training}")

The balanced accuracy score for testing: 1.0
The balanced accuracy score for testing: 0.975609756097561

## 10. Calculate and print the precision score for both the training and the testing set.

In [77]:
# Your code here :
from sklearn.metrics import precision_score

ps_testing = precision_score(y_test, y_pred_test, average='weighted')

ps_training = precision_score(y_train, y_pred_train, average='weighted')


print(f"The precision score for testing: {ps_testing}")
print(f"The precision score for testing: {ps_training}")

The precision score for testing: 1.0
The precision score for testing: 0.9767857142857144

## 11. Calculate and print the recall score for both the training and the testing set.

In [70]:
# Your code here :
from sklearn.metrics import recall_score

rs_testing = recall_score(y_test, y_pred_test, average='weighted')

rs_training = recall_score(y_train, y_pred_train, average='weighted')


print(f"The recall score for testing: {rs_testing}")
print(f"The recall score for training: {rs_training}")

The recall score for testing: 1.0
The recall score for training: 0.975

## 12. Calculate and print the F1 score for both the training and the testing set.

In [73]:
# Your code here :
from sklearn.metrics import f1_score

f1s_testing = f1_score(y_test, y_pred_test, average='weighted')

f1s_training = f1_score(y_train, y_pred_train, average='weighted')


print(f"The f1-score for testing: {f1s_testing}")
print(f"The f1-score for training: {f1s_training}")

The f1-score for testing: 1.0
The f1-score for training: 0.9749882794186592

## 13. Generate confusion matrices for both the training and the testing set.

In [75]:
# Your code here :
from sklearn.metrics import confusion_matrix

cmx_testing = confusion_matrix(y_test, y_pred_test)

cmx_training = confusion_matrix(y_train, y_pred_train)


print(f"The f1-score for testing: {cmx_testing}")
print(f"The f1-score for training: {cmx_training}")

The f1-score for testing: [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
The f1-score for training: [[40  0  0]
 [ 0 38  3]
 [ 0  0 39]]

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [80]:
# Have fun here !
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score

knn_model = KNeighborsClassifier(n_neighbors=5)

knn_model.fit(X_train, y_train)

knn_predict = knn_model.predict(X_test)

# knn_evaluation = accuracy_score(knn_predict, X_test)

ps_logr = precision_score(y_test, y_pred_test, average='weighted')
ps_knn = precision_score(y_test, knn_predict, average='weighted')

metrics = {
  "Logistic Regression": ps_logr,
  "KNN": ps_knn
}

for model, score in metrics.items():
  print(f"{model} Precission: {score}")

Logistic Regression Precission: 1.0
KNN Precission: 1.0