# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [115]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Regression Model Evaluation

In [116]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [117]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [118]:
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [119]:
from sklearn.model_selection import train_test_split as tts
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import mean_absolute_error as mae

In [120]:
data.dtypes

CRIM       float64
ZN         float64
INDUS      float64
CHAS         int64
NOX        float64
RM         float64
AGE        float64
DIS        float64
RAD          int64
TAX        float64
PTRATIO    float64
B          float64
LSTAT      float64
MEDV       float64
dtype: object

In [121]:
data.shape

(506, 14)

In [122]:
data.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [123]:
# So, we wanna get MEDV as the value to predict:

X, y= data.drop("MEDV", axis= 1), data["MEDV"]
X_train, X_test, y_train, y_test= tts(X, y, test_size= 0.2, random_state= 69)

print(f"X-shape: {X.shape} --- X_train-shape: {X_train.shape} --- X_test-shape: {X_test.shape}")
print(f"y-shape: {y.shape} --- y_train-shape: {y_train.shape} --- y_test-shape: {y_test.shape}")

X-shape: (506, 13) --- X_train-shape: (404, 13) --- X_test-shape: (102, 13)
y-shape: (506,) --- y_train-shape: (404,) --- y_test-shape: (102,)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [124]:
# Your code here :
model= LinearRegression()
model.fit(X, y)

print(model.intercept_, model.coef_)

36.45948838508963 [-1.08011358e-01  4.64204584e-02  2.05586264e-02  2.68673382e+00
 -1.77666112e+01  3.80986521e+00  6.92224640e-04 -1.47556685e+00
  3.06049479e-01 -1.23345939e-02 -9.52747232e-01  9.31168327e-03
 -5.24758378e-01]

## 3. Calculate and print R-squared for both the training and the testing set.

In [125]:
# Your code here :
r2_train, r2_test= model.score(X_train, y_train), model.score(X_test, y_test)

print("R² on train:", round(r2_train, 4))
print("R² on test:", round(r2_test, 4))

R² on train: 0.7514
R² on test: 0.6889

## 4. Calculate and print mean squared error for both the training and the testing set.

In [126]:
y_train_pred= model.predict(X_train)
y_test_pred= model.predict(X_test)

In [127]:
# Your code here :
mse_train, mse_test= mse(y_train, y_train_pred), mse(y_test, y_test_pred)

print("Mean² error on train:", round(mse_train, 4))
print("Mean² error on test:", round(mse_test, 4))

Mean² error on train: 21.7655
Mean² error on test: 22.407

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [128]:
# Your code here :
mae_train, mae_test= mae(y_train, y_train_pred), mae(y_test, y_test_pred)

print("Mean absolute error on train:", round(mae_train, 4))
print("Mean² absolute on test:", round(mae_test, 4))

Mean absolute error on train: 3.3101
Mean² absolute on test: 3.1156

## Classification Model Evaluation

In [129]:
from sklearn.datasets import load_iris
data = load_iris()

In [130]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [131]:
column_names = data.feature_names

In [132]:
df = pd.DataFrame(data['data'],columns=column_names)

In [133]:
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [134]:
target = pd.DataFrame(data.target)

In [135]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [136]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [137]:
# Your code here :
X, y= data["data"], data["target"]
X_train, X_test, y_train, y_test= tts(X, y, test_size=0.2, random_state= 69)

print(f"X-shape: {X.shape} --- X_train-shape: {X_train.shape} --- X_test-shape: {X_test.shape}")
print(f"y-shape: {y.shape} --- y_train-shape: {y_train.shape} --- y_test-shape: {y_test.shape}")

X-shape: (150, 4) --- X_train-shape: (120, 4) --- X_test-shape: (30, 4)
y-shape: (150,) --- y_train-shape: (120,) --- y_test-shape: (30,)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [138]:
# Your code here :
model= LogisticRegression()
model.fit(X_train, y_train)

print(model.intercept_, model.coef_)

[  9.4189915    2.12423155 -11.54322305] [[-0.45028378  0.88878419 -2.33472771 -1.0095538 ]
 [ 0.58224169 -0.48472553 -0.17348367 -0.90974806]
 [-0.13195791 -0.40405865  2.50821138  1.91930186]]

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [139]:
from sklearn.metrics import accuracy_score, balanced_accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
y_train_pred= model.predict(X_train)
y_test_pred= model.predict(X_test)

In [140]:
# Your code here :
acc_train, acc_test= accuracy_score(y_train, y_train_pred), accuracy_score(y_test, y_test_pred)

print("Accuracy score on train:", round(acc_train, 4))
print("Accuracy score on test:", round(acc_test, 4))

Accuracy score on train: 0.9583
Accuracy score on test: 0.9667

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [141]:
# Your code here :
bal_train, bal_test= balanced_accuracy_score(y_train, y_train_pred), balanced_accuracy_score(y_test, y_test_pred)

print("Balanced accuracy score on train:", round(bal_train, 4))
print("Balanced accuracy score on test:", round(bal_test, 4))

Balanced accuracy score on train: 0.9586
Balanced accuracy score on test: 0.9722

## 10. Calculate and print the precision score for both the training and the testing set.

In [142]:
# Your code here :
prec_train, prec_test= precision_score(y_train, y_train_pred, average="weighted"), precision_score(y_test, y_test_pred, average="weighted")

print("Precission score on train:", round(prec_train, 4))
print("Precission accuracy score on test:", round(prec_test, 4))

Precission score on train: 0.9586
Precission accuracy score on test: 0.9704

## 11. Calculate and print the recall score for both the training and the testing set.

In [143]:
# Your code here :
recall_tain, recall_test= recall_score(y_train, y_train_pred, average="weighted"), recall_score(y_test, y_test_pred, average="weighted")

print("Recall score on train:", round(recall_tain, 4))
print("Recall accuracy score on test:", round(recall_test, 4))

Recall score on train: 0.9583
Recall accuracy score on test: 0.9667

## 12. Calculate and print the F1 score for both the training and the testing set.

In [144]:
# Your code here :
f1_train, f1_test= f1_score(y_train, y_train_pred, average="weighted"), f1_score(y_test, y_test_pred, average="weighted")

print("F1 score on train:", round(f1_train, 4))
print("F1 accuracy score on test:", round(f1_test, 4))

F1 score on train: 0.9584
F1 accuracy score on test: 0.9669

## 13. Generate confusion matrices for both the training and the testing set.

In [148]:
# Your code here :
conma_train, conma_test= confusion_matrix(y_train, y_train_pred), confusion_matrix(y_test, y_test_pred)

print("Confusion matrix on train:\n", conma_train)
print("Confusion matrix on test:\n", conma_test)

Confusion matrix on train:
 [[40  0  0]
 [ 0 39  3]
 [ 0  2 36]]
Confusion matrix on test:
 [[10  0  0]
 [ 0  8  0]
 [ 0  1 11]]

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [ ]:
# Have fun here !