# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Regression Model Evaluation

In [2]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [3]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [4]:
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X = data.drop(columns=['MEDV']) # Features (X)
y = data['MEDV']                # Target variable (y)

In [7]:
#Split the data: 20% (0.2) testing and the rest 80% training
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

#Verify the split
print(X_train.shape)
print(X_test.shape)

(404, 13)
(102, 13)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
# Create and train the model
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [10]:
# Use the model 'model' to generate predictions on the sets
train_predict = model.predict(X_train)
test_predict = model.predict(X_test)

# Verify
print(train_predict[:10])     # Numpy has no 'head' attribute, so we simulate it using python list slicing
print(test_predict[:10])

[10.96952405 19.41196567 23.06419602 12.1470648  18.3738116  25.24677946
 20.77024774 23.90932632  7.81713319 19.60988098]
[28.99672362 36.02556534 14.81694405 25.03197915 18.76987992 23.25442929
 17.66253818 14.34119    23.01320703 20.63245597]

## 3. Calculate and print R-squared for both the training and the testing set.

In [11]:
train_r2 = model.score(X_train, y_train)
test_r2 = model.score(X_test, y_test)

print(f'Train R-squared: {train_r2}')
print(f'Test R-squared: {test_r2}')

Train R-squared: 0.7508856358979672
Test R-squared: 0.6687594935356289

## 4. Calculate and print mean squared error for both the training and the testing set.

In [12]:
from sklearn.metrics import mean_squared_error

In [13]:
train_mse = mean_squared_error(y_train, train_predict)
test_mse = mean_squared_error(y_test, test_predict)

print(f'Train MSE: {train_mse}')
print(f'Test MSE: {test_mse}')
print()
print(f'Train RMSE: {train_mse ** 0.5}')    # Power of 0.5 is equal to square root
print(f'Test RMSE: {test_mse ** 0.5}')

Train MSE: 21.641412753226316
Test MSE: 24.29111947497374

Train RMSE: 4.6520331848801675
Test RMSE: 4.928602182665359

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [14]:
from sklearn.metrics import mean_absolute_error

In [15]:
train_mae = mean_absolute_error(y_train, train_predict)
test_mae = mean_absolute_error(y_test, test_predict)

print(f'Train MAE: {train_mae}')
print(f'Test MAE: {test_mae}')

Train MAE: 3.314771626783233
Test MAE: 3.189091965887874

## Classification Model Evaluation

In [16]:
from sklearn.datasets import load_iris
data = load_iris()

In [17]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [18]:
column_names = data.feature_names

In [19]:
df = pd.DataFrame(data['data'],columns=column_names)

In [20]:
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [21]:
target = pd.DataFrame(data.target)

In [22]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [23]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [24]:
X = df
y = target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=42)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [25]:
from sklearn.linear_model import LogisticRegression

In [26]:
log_reg_model = LogisticRegression()
log_reg_model.fit(X_train, y_train.values.ravel())  # Convert into raw data with '.values' and turn it into a list with '.ravel()'

LogisticRegression()

In [27]:
train_predict = log_reg_model.predict(X_train)
test_predict = log_reg_model.predict(X_test)

print(train_predict[:10])
print(test_predict[:10])

[0 0 1 0 0 2 1 0 0 0]
[1 0 2 1 1 0 1 2 1 1]

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [28]:
from sklearn.metrics import accuracy_score

In [29]:
train_accuracy = accuracy_score(y_train.values.ravel(), train_predict)
test_accuracy = accuracy_score(y_test.values.ravel(), test_predict)

print(f'Train accuracy: {train_accuracy}')
print(f'Test accuracy: {test_accuracy}')

Train accuracy: 0.975
Test accuracy: 1.0

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [30]:
from sklearn.metrics import balanced_accuracy_score

In [31]:
train_accuracy_balanced = balanced_accuracy_score(y_train.values.ravel(), train_predict)
test_accuracy_balanced = balanced_accuracy_score(y_test.values.ravel(), test_predict)

print(f'Train accuracy: {train_accuracy_balanced}')
print(f'Test accuracy: {test_accuracy_balanced}')

Train accuracy: 0.975609756097561
Test accuracy: 1.0

## 10. Calculate and print the precision score for both the training and the testing set.

In [32]:
from sklearn.metrics import precision_score

In [33]:
train_precision = precision_score(y_train.values.ravel(), train_predict, average='weighted')
test_precision = precision_score(y_test.values.ravel(), test_predict, average="weighted")

print(f'Train precision: {train_precision}')
print(f'Test precision: {test_precision}')

Train precision: 0.9767857142857144
Test precision: 1.0

## 11. Calculate and print the recall score for both the training and the testing set.

In [34]:
from sklearn.metrics import recall_score

In [35]:
train_recall = recall_score(y_train.values.ravel(), train_predict, average='weighted')
test_recall = recall_score(y_test.values.ravel(), test_predict, average='weighted')

print(f'Train recall: {train_recall}')
print(f'Test recall: {test_recall}')

Train recall: 0.975
Test recall: 1.0

## 12. Calculate and print the F1 score for both the training and the testing set.

In [36]:
from sklearn.metrics import f1_score

In [41]:
train_f1 = f1_score(y_train.values.ravel(), train_predict, average='weighted')
test_f1 = f1_score(y_test.values.ravel(), test_predict, average='weighted')

print(f'Train F1: {train_f1}')
print(f'Test F1: {test_f1}')

Train F1: 0.9749882794186592
Test F1: 1.0

## 13. Generate confusion matrices for both the training and the testing set.

In [38]:
from sklearn.metrics import confusion_matrix

In [43]:
train_cm = confusion_matrix(y_train.values.ravel(), train_predict)
test_cm = confusion_matrix(y_test.values.ravel(), test_predict)

print(f'Train Confusion Matrix: \n{train_cm}')
print(f'Test Confusion Matrix: \n{test_cm}')

Train Confusion Matrix:
[[40  0  0]
 [ 0 38  3]
 [ 0  0 39]]
Test Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [40]:
# Have fun here !