# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [1]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Regression Model Evaluation

In [2]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [3]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [4]:
data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [124]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression 
from sklearn.linear_model import LogisticRegression

In [10]:
X= data.drop("MEDV", axis=1)
y=data['MEDV']

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=42)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [15]:
model = LinearRegression()
model.fit(X_train, y_train)
y_test_pred = model.predict(X_test)
y_train_pred = model.predict(X_train)

## 3. Calculate and print R-squared for both the training and the testing set.

In [21]:
from sklearn.metrics import r2_score

print("R2:", round(r2_score(y_test, y_test_pred), 3))
print("R2:", round(r2_score(y_train, y_train_pred),3))

R2: 0.669
R2: 0.751

## 4. Calculate and print mean squared error for both the training and the testing set.

In [25]:
from sklearn.metrics import mean_squared_error

print("MSE", round(mean_squared_error(y_test, y_test_pred),3))
print("MSE", round(mean_squared_error(y_train, y_train_pred),3))

MSE 24.291
MSE 21.641

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [26]:
from sklearn.metrics import mean_absolute_error

print("MAE", round(mean_absolute_error(y_test, y_test_pred),3))
print("MAE", round(mean_absolute_error(y_train, y_train_pred),3))

MAE 3.189
MAE 3.315

## Classification Model Evaluation

In [109]:
from sklearn.datasets import load_iris
data = load_iris(as_frame=True)
df = data.frame.copy()

In [110]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [111]:
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

In [112]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)', 'target'],
      dtype='object')

In [113]:
df['target'].keys()

RangeIndex(start=0, stop=150, step=1)

In [114]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [115]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [116]:
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [118]:
X= df.drop("target", axis=1)
y=df['target']

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=42)

In [125]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_test_pred = model.predict(X_test)
y_train_pred = model.predict(X_train)

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [127]:
from sklearn.metrics import accuracy_score

print("Accuracy score test:", round(accuracy_score(y_test,y_test_pred), 3))
print("Accuracy score train:", round(accuracy_score(y_train, y_train_pred),3))

Accuracy score test: 1.0
Accuracy score train: 0.975

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [132]:
from sklearn.metrics import balanced_accuracy_score

print("Balanced accuracy score test:", round(balanced_accuracy_score(y_test,y_test_pred), 3))
print("Balanced accuracy score train:", round(balanced_accuracy_score(y_train, y_train_pred),3))

Balanced accuracy score test: 1.0
Balanced accuracy score train: 0.976

## 10. Calculate and print the precision score for both the training and the testing set.

In [134]:
from sklearn.metrics import precision_score

print("Precision score test:", round(precision_score(y_test,y_test_pred, average='macro'), 3))
print("Precision score train:", round(precision_score(y_train, y_train_pred, average='macro'),3))

Precision score test: 1.0
Precision score train: 0.976

## 11. Calculate and print the recall score for both the training and the testing set.

In [136]:
from sklearn.metrics import recall_score

print("Recall score test:", round(recall_score(y_test,y_test_pred, average='macro'), 3))
print("Recall score train:", round(recall_score(y_train, y_train_pred, average='macro'),3))

Recall score test: 1.0
Recall score train: 0.976

## 12. Calculate and print the F1 score for both the training and the testing set.

In [137]:
from sklearn.metrics import f1_score

print("F1 score test:", round(recall_score(y_test,y_test_pred, average='macro'), 3))
print("F1 score train:", round(recall_score(y_train, y_train_pred, average='macro'),3))

F1 score test: 1.0
F1 score train: 0.976

## 13. Generate confusion matrices for both the training and the testing set.

In [140]:
from sklearn.metrics import confusion_matrix

cm_train = confusion_matrix(y_train, y_train_pred)
cm_test = confusion_matrix(y_test, y_test_pred)

print("Confusion matrix (Train):\n", cm_train)
print("\nConfusion matrix (Test):\n", cm_test)

Confusion matrix (Train):
 [[40  0  0]
 [ 0 38  3]
 [ 0  0 39]]

Confusion matrix (Test):
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]