# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [14]:
import pandas as pd
import numpy as np
import warnings

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


warnings.filterwarnings('ignore')

## Regression Model Evaluation

In [2]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [3]:
data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [3]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [ ]:
# Your code here :
X = data[data.columns[:-1]]
y = data[[data.columns[-1]]]

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=15, test_size=0.2)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [ ]:
# Your code here :#
#### Model definition and training
MEDV_linReg = LinearRegression()
MEDV_linReg.fit(X_train, y_train)

### Make predictions
y_pred_train = MEDV_linReg.predict(X_train)
y_pred_test = MEDV_linReg.predict(X_test)

## 3. Calculate and print R-squared for both the training and the testing set.

In [45]:
# Your code here :
def Reg_eval(X_train, y_train, MEDV_linReg):
    from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
    
    ### Make predictions
    y_pred_train = MEDV_linReg.predict(X_train)

    r2_score = float(round(r2_score(y_train, y_pred_train),2))
    RMSE = float(round(np.sqrt(mean_squared_error(y_pred_train, y_train)),2))
    MAE = float(round(mean_absolute_error(y_pred_train, y_train),2))

    reg_scores = pd.DataFrame([r2_score, RMSE, MAE], index=['r2_score', 'RMSE', 'MAE'])
    return reg_scores.T

reg_scores_train = Reg_eval(X_train, y_train, MEDV_linReg)
reg_scores_test = Reg_eval(X_test, y_test, MEDV_linReg)

print(f'r2_score train: {reg_scores_train['r2_score'].values[0]}| r2_score test: {reg_scores_test['r2_score'].values[0]}')

r2_score train: 0.75| r2_score test: 0.69

## 4. Calculate and print mean squared error for both the training and the testing set.

In [44]:
# Your code here :
print(f'RMSE train: {reg_scores_train['RMSE'].values[0]}| RMSE test: {reg_scores_test['RMSE'].values[0]}')

RMSE train: 4.68| RMSE test: 4.88

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [46]:
# Your code here :
print(f'MAE train: {reg_scores_train['MAE'].values[0]}| MAE test: {reg_scores_test['MAE'].values[0]}')

MAE train: 3.31| MAE test: 3.69

## Classification Model Evaluation

In [47]:
from sklearn.datasets import load_iris
data = load_iris()

In [48]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [49]:
column_names = data.feature_names
column_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [50]:
df = pd.DataFrame(data['data'],columns=column_names)

In [51]:
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [52]:
target = pd.DataFrame(data.target)

In [53]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [54]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [59]:
# Your code here :
X_train, X_test, y_train, y_test = train_test_split(df, target, random_state=15, test_size=0.2)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [62]:
# Your code here :

from sklearn.linear_model import LogisticRegression

log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

y_pred_train = log_reg.predict(X_train)
y_pred_test = log_reg.predict(X_test)

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [ ]:
# Your code here :
from sklearn.metrics import classification_report, confusion_matrix
print("Logistic Regression Report:\n", classification_report(y_test, y_pred_test))

Logistic Regression Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00         9

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

In [89]:
def Class_eval(X_train, y_train, MEDV_linReg):
    from sklearn.metrics import accuracy_score, precision_score, recall_score, balanced_accuracy_score, f1_score
    
    ### Make predictions
    y_pred_train = MEDV_linReg.predict(X_train)

    accuracy_score = round(accuracy_score(y_train, y_pred_train),2)
    balanced_accuracy_score = round(balanced_accuracy_score(y_train, y_pred_train),2)
    
    precision_score = float(round(precision_score(y_train, y_pred_train, average='macro'),2))
    recall_score = float(round(recall_score(y_train, y_pred_train, average='macro'),2))
    f1_score = float(round(f1_score(y_train, y_pred_train, average='macro'),2))

    class_scores = pd.DataFrame([accuracy_score, balanced_accuracy_score, precision_score, recall_score, f1_score], index=['accuracy_score', 'balanced_accuracy_score', 'precision_score', 'recall_score', 'f1_score'])
    return class_scores.T

class_scores_train = Class_eval(X_train, y_train, log_reg)
class_scores_test = Class_eval(X_test, y_test, log_reg)

print(f'accuracy_score train: {class_scores_train['accuracy_score'].values[0]}| accuracy_score test: {class_scores_test['accuracy_score'].values[0]}')

accuracy_score train: 0.97| accuracy_score test: 1.0

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [90]:
# Your code here :
print(f'balanced_accuracy_score train: {class_scores_train['balanced_accuracy_score'].values[0]}| balanced_accuracy_score test: {class_scores_test['balanced_accuracy_score'].values[0]}')

balanced_accuracy_score train: 0.97| balanced_accuracy_score test: 1.0

## 10. Calculate and print the precision score for both the training and the testing set.

In [91]:
# Your code here :
print(f'precision_score train: {class_scores_train['precision_score'].values[0]}| precision_score test: {class_scores_test['precision_score'].values[0]}')

precision_score train: 0.98| precision_score test: 1.0

## 11. Calculate and print the recall score for both the training and the testing set.

In [92]:
# Your code here :
print(f'recall_score train: {class_scores_train['recall_score'].values[0]}| recall_score test: {class_scores_test['recall_score'].values[0]}')

recall_score train: 0.97| recall_score test: 1.0

## 12. Calculate and print the F1 score for both the training and the testing set.

In [93]:
# Your code here :
print(f'f1_score train: {class_scores_train['f1_score'].values[0]}| f1_score test: {class_scores_test['f1_score'].values[0]}')

f1_score train: 0.97| f1_score test: 1.0

## 13. Generate confusion matrices for both the training and the testing set.

In [97]:
# Your code here :
confusion_matrix(y_train, y_pred_train)

array([[42,  0,  0],
       [ 0, 34,  3],
       [ 0,  0, 41]])

In [98]:
confusion_matrix(y_test, y_pred_test)

array([[ 8,  0,  0],
       [ 0, 13,  0],
       [ 0,  0,  9]])

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [26]:
# Have fun here !