# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [200]:
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## Regression Model Evaluation

In [201]:
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']
data = pd.read_csv('housing.csv', header=None, delimiter=r"\s+", names=column_names)

In [202]:
"""
CRIM - per capita crime rate by town
ZN - proportion of residential land zoned for lots over 25,000 sq.ft.
INDUS - proportion of non-retail business acres per town.
CHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)
NOX - nitric oxides concentration (parts per 10 million)
RM - average number of rooms per dwelling
AGE - proportion of owner-occupied units built prior to 1940
DIS - weighted distances to five Boston employment centres
RAD - index of accessibility to radial highways
TAX - full-value property-tax rate per $10,000
PTRATIO - pupil-teacher ratio by town
B - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town
LSTAT - % lower status of the population
MEDV - Median value of owner-occupied homes in $1000's"""

"\nCRIM - per capita crime rate by town\nZN - proportion of residential land zoned for lots over 25,000 sq.ft.\nINDUS - proportion of non-retail business acres per town.\nCHAS - Charles River dummy variable (1 if tract bounds river; 0 otherwise)\nNOX - nitric oxides concentration (parts per 10 million)\nRM - average number of rooms per dwelling\nAGE - proportion of owner-occupied units built prior to 1940\nDIS - weighted distances to five Boston employment centres\nRAD - index of accessibility to radial highways\nTAX - full-value property-tax rate per $10,000\nPTRATIO - pupil-teacher ratio by town\nB - 1000(Bk - 0.63)^2 where Bk is the proportion of blacks by town\nLSTAT - % lower status of the population\nMEDV - Median value of owner-occupied homes in $1000's"

In [203]:
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [204]:
# Your code here :
from sklearn.model_selection import train_test_split

X = data.drop(columns='MEDV', axis=1)
y = data['MEDV']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=23)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [205]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

train_prediction = model.predict(X_train)
test_prediction = model.predict(X_test)

print(train_prediction)
print(test_prediction)

[30.75150781 39.71551247 18.63094211 19.9057684  32.71031491 22.97074531
 20.24905183 18.31812302 23.96588501 19.35059282 30.54435948 19.33865168
 24.67320123 26.28060414 12.58997035 21.19386238 25.80544121 21.01745472
 22.2101958  18.01270093 18.83323224 25.09203252 11.61913738 25.55977672
 16.20433739 21.09242593 28.90465292 17.91469768 29.33938791 21.1695621
  1.7236041  21.1002392  18.6883258  18.99455    23.04658708 15.7319515
 23.06661839 36.9332386  15.25012279 31.54304304 36.08804125  6.28916926
 22.34898067 33.32977464 30.6864192  25.21745952  6.01749325  8.52292323
 34.09514576 33.8806446  27.65942557 36.0314232  23.97642832 25.72466968
 14.83411799  4.34146449 16.83378087 15.91030009 24.51091011 19.68813417
 21.24523481 20.45281462 14.49681057 10.94730581 28.93982517  8.54127323
 25.85077719 23.80810672 11.77499773 34.03639385 17.61945886 27.34994018
 27.07854249 17.0602306  19.32042383 25.21763827 32.10989497 26.68579553
 17.28045604 23.77873428 11.50265461 21.81930234 21.10443211 28.23746441
 27.95884645 26.11740296 20.7183029  22.93531814  9.05512607 22.25833431
 34.72703979 24.39094831 24.87543114 25.65245448 28.39711988 11.67009155
 28.02709194 24.16813927 19.7005958  41.76367224 18.5712305  20.57883322
 20.80787723 17.14999035 36.67785178 18.75606034 23.30458452 35.38547282
 25.30450401 18.59218225 14.39040073 27.20597382 19.80082858 28.79035272
 22.76832094 32.73036649 18.58694324 22.48590259 19.89223752 22.7508865
 17.2071114  25.53261091 21.09641022 40.63588367 27.36216158 13.61643683
  9.97800725 19.90035099 36.8494792   7.67562103 24.0826404  24.84189364
 20.567155   31.49373909 27.55832739 19.77050198 25.43718791 29.23279098
 20.48035884 22.13075982 15.90402779 24.5833925  15.59969085 11.88617783
 17.91778764  6.55348002 23.80479765 29.05776425 15.90916355 28.44687967
  7.9179645  21.52445613 36.00847361 17.44653084 19.75479454 30.94014953
 20.72358524 22.39994765 19.05070848 38.58328634 22.52331566 30.98401862
 24.95133344 26.9827495  21.65508626 -4.36096149 40.4048542  42.4327804
 21.41751315  3.97142353 32.48321408 21.47264836 21.50720774 17.94850436
 25.01992108  9.84326836 32.75622313 24.39610619 27.33305981 19.28368398
 23.40592184 15.12542096 28.71659187 16.05875591 35.25904249 27.17501469
 22.67829753 16.05946999 23.69460309 26.66462257  9.29654772 20.98000475
 23.32446105 15.12399614 20.05873215  6.59627598 20.21267528 20.42032847
 25.2983521  24.58213472 19.3120474  34.63910262 20.04044911 23.3848931
 20.87081141  7.45047603 30.72049987 24.87857541 22.25111728 14.87936677
 17.13680989 16.8421969  26.76656874 12.687413   30.42245718 24.05951979
 33.43754391 33.84249277 18.22111895 25.26379504 13.12379625 13.04979266
 20.23700587 24.78229335 13.44985675 25.09679904 14.11418384 18.64255199
 14.07822877 22.15898624 14.43320287 21.70582245 34.67765971 20.14891042
 25.21648932 32.47143354 14.34435146 32.33485431 27.99234237 13.97044176
 25.79074224 23.51507445 14.42963934 21.82412729 26.14177144 21.50107167
 26.51317753 30.49483764 28.63475214 23.9299416  23.75249131 14.43951351
 31.02461759 21.99480645 16.97212131 22.51915931 30.3934183  33.65346019
 18.36712867 20.95203821 27.27801213 22.67099876  6.42354331 20.48875198
 13.04446994 34.59676277 23.76893816 24.17173299 20.52697389 26.85959379
 33.03154441 22.42588349 27.8669209  22.94376174 34.26637348 19.22959437
 21.84281842 31.24321196 19.50295821 23.70998346 33.93263475  0.7316677
 38.34427796 16.99664465 35.25202111 30.23605874 37.48245408 41.3107496
 29.87060367 14.06446676 22.88874485 16.0828366  30.34217997 35.5352468
 17.26399307 29.19727678 27.98352757 17.21558043 25.16447247 27.45219123
 17.60248607 35.11197841 34.56535806 27.79917252 14.26485138 24.31790697
 28.39075942 23.49899226 29.77345243 23.27613133 40.71205366 18.78499448
 27.89961576 25.17346841 21.44218158 20.25292855 19.41321792 33.56095993
 16.24705183 18.35697565 20.32001976 17.72366371 11.40382704 35.49891321
 16.58718723 20.12502268 21.93262601 37.12158765 31.88073982 16.60705026
 24.13428315 24.37222118 44.96497055 23.09986249 25.37919832 20.16457039
 21.59866276 17.62442703 14.416494   18.05395222 14.76262055  8.5623667
 14.71030556  8.65134144 30.14095522 20.91296396 18.69872754 37.24389315
 15.9531241  17.55223346 26.34788091 25.09529835 24.07119079 22.27481464
 19.98742217 13.59789873 20.58361885 35.75106483 17.59140791 20.81821816
 10.49236487 19.64646499 24.37324561 27.15732723  7.97947504 30.59996067
 22.51891716 10.60783784 16.82108996 33.69504175  6.91615756 13.30664837
 33.01776013 17.67617836 15.036531   22.88302407 19.39452602  8.7185258
 17.97223609 20.6866552  33.095378   32.50159964 18.9713058  18.66097868
 31.64336305 17.13389791 20.53575663 12.86945422 16.97818793 22.83856875
 13.0721234  16.75061736 27.33861959 31.51774283 25.47172306 19.0069835
 32.74744303 18.40813325 12.87239454  4.30938185 12.83566966 34.35862092
 24.50740967 25.35888587]
[25.61587252 27.12586692 27.2088525  16.76603362 38.00811547 17.05443719
 20.26113342 28.70919709 33.96194692 37.65615799 16.21901641 27.51736638
 25.7187111  26.43299408 21.31864713 20.01859619 30.87402793 30.98608893
 29.23266456 28.95514577 18.96926991 17.33534451 24.74641894 24.21793059
 13.8394873  22.78879429 32.94398003 28.62425477 29.11102704 38.11386992
 18.22086333 15.67529394 20.0137507  20.30595835 20.53027273 37.07808
 25.45522971 31.21980602 13.76404735 36.06105193  8.85561067 13.50823899
 11.35806828 19.64395577 35.88548656 20.30249401 13.0696301  22.12998418
 12.74438772 38.93664974 22.73399592  3.30910813 17.58596169 18.29423866
 24.13601366 32.74378072  5.53761184 21.52990404 17.81376459 22.31765421
 17.9309305  21.51118474 20.93420687 42.69323506 30.72062844 29.52582704
 20.45099249 16.5047906  30.89037231 14.12930467 20.27573153 11.00666366
 21.93241329 18.63703789 15.85233969 14.08091012 14.93188705 23.48466571
 13.10674564 32.02338044 23.10506853 25.5961718  25.09756853 12.32727247
 22.46185725 21.24709959 36.22525835 40.25079579 29.30312518 16.38918008
 16.38615981 20.72277336 20.71664588 19.30088389 24.20833923 13.66921042
 42.91672981 17.23760986 27.68885365 25.08605564 17.71101551 23.19018216]

## 3. Calculate and print R-squared for both the training and the testing set.

In [206]:
# Your code here :
from sklearn.metrics import r2_score

r2_train = r2_score(y_train, train_prediction)
r2_test = r2_score(y_test, test_prediction)

print(r2_train)
print(r2_test)

0.7377734707180097
0.7451430642919579

## 4. Calculate and print mean squared error for both the training and the testing set.

In [207]:
# Your code here :
from sklearn.metrics import mean_squared_error

mse_train = mean_squared_error(y_train, train_prediction)
mse_test = mean_squared_error(y_test, test_prediction)

print(mse_train)
print(mse_test)

22.021884616145645
21.953471731537025

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [208]:
# Your code here :
from sklearn.metrics import mean_absolute_error

mba_train = mean_absolute_error(y_train, train_prediction)
mba_test = mean_absolute_error(y_test, test_prediction)

print(mba_train)
print(mba_test)

3.24017598721723
3.668988671078469

## Classification Model Evaluation

In [209]:
from sklearn.datasets import load_iris
data = load_iris()

In [210]:
print(data.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
============== ==== ==== ======= ===== ====================

:Missing Attribute Values: None
:Class Distribution: 33.3% for each of 3 classes.
:Creator: R.A. Fisher
:Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
:Date: July, 1988

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.

.. dropdown:: References

  - Fisher, R.A. "The use of multiple measurements in taxonomic problems"
    Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
    Mathematical Statistics" (John Wiley, NY, 1950).
  - Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
    (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
  - Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
    Structure and Classification Rule for Recognition in Partially Exposed
    Environments".  IEEE Transactions on Pattern Analysis and Machine
    Intelligence, Vol. PAMI-2, No. 1, 67-71.
  - Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
    on Information Theory, May 1972, 431-433.
  - See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
    conceptual clustering system finds 3 classes in the data.
  - Many, many more ...

In [211]:
column_names = data.feature_names

In [212]:
df = pd.DataFrame(data['data'],columns=column_names)

In [213]:
df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [214]:
target = pd.DataFrame(data.target)

In [215]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [216]:
data['target_names']

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [217]:
# Your code here :
from sklearn.model_selection import train_test_split

X = df.values
y = target.values.ravel()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=23)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [218]:
# Your code here :
from sklearn.linear_model import LogisticRegression

logi_model = LogisticRegression()
logi_model.fit(X_train, y_train)

logi_train_prediction = logi_model.predict(X_train)
logi_test_prediction = logi_model.predict(X_test)

print(logi_train_prediction)
print(logi_test_prediction)

[0 1 0 2 0 0 1 1 1 2 2 0 1 0 1 2 1 2 0 1 2 2 0 2 1 1 2 1 0 2 2 0 1 0 2 1 1
 2 2 1 0 0 2 0 0 2 2 1 0 1 2 1 2 2 1 0 1 2 2 1 0 1 1 1 2 2 1 2 2 2 0 2 1 0
 2 2 0 1 1 2 0 0 1 0 1 1 0 2 1 1 0 2 1 2 2 1 0 0 2 2 1 0 2 1 2 1 0 0 0 2 0
 0 2 0 1 0 1 0 0 2]
[2 2 1 0 2 1 0 2 0 1 1 0 2 0 0 2 1 1 2 0 2 0 0 0 2 0 0 2 1 1]

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [219]:
# Your code here :
from sklearn import metrics

acc_test = metrics.accuracy_score(y_test, logi_test_prediction)
acc_train =metrics.accuracy_score(y_train, logi_train_prediction)

print(acc_test)
print(acc_train)

1.0
0.9666666666666667

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [220]:
# Your code here :
bal_acc_test = metrics.balanced_accuracy_score(y_test, logi_test_prediction)
bal_acc_train =metrics.balanced_accuracy_score(y_train, logi_train_prediction)

print(bal_acc_test)
print(bal_acc_train)

1.0
0.9678571428571429

## 10. Calculate and print the precision score for both the training and the testing set.

In [221]:
# Your code here :
prec_score_test = metrics.precision_score(y_test, logi_test_prediction, average='macro')
prec_score_train =metrics.precision_score(y_train, logi_train_prediction, average='macro')

print(prec_score_test)
print(prec_score_train)

1.0
0.9678571428571429

## 11. Calculate and print the recall score for both the training and the testing set.

In [222]:
# Your code here :
recall_score_test = metrics.recall_score(y_test, logi_test_prediction, average='macro')
recall_score_train =metrics.recall_score(y_train, logi_train_prediction, average='macro')

print(recall_score_test)
print(recall_score_train)

1.0
0.9678571428571429

## 12. Calculate and print the F1 score for both the training and the testing set.

In [223]:
# Your code here :
f1_score_test = metrics.f1_score(y_test, logi_test_prediction, average='macro')
f1_score_train =metrics.f1_score(y_train, logi_train_prediction, average='macro')

print(f1_score_test)
print(f1_score_train)

1.0
0.9674796747967479

## 13. Generate confusion matrices for both the training and the testing set.

In [224]:
# Your code here :
from sklearn.metrics import confusion_matrix

conf_matrix_train = metrics.confusion_matrix(y_train, logi_train_prediction)
conf_matrix_test = metrics.confusion_matrix(y_test, logi_test_prediction)

print(conf_matrix_train)
print(conf_matrix_test)

[[38  0  0]
 [ 0 39  3]
 [ 0  1 39]]
[[12  0  0]
 [ 0  8  0]
 [ 0  0 10]]

## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.

In [225]:
# Have fun here !